'@beapi/core':
  - 'packages/beapi/*'
  - 'packages/beapi/**/*'

'@beapi/scaffolder':
  - 'packages/create-beapi/*'
  - 'packages/create-beapi/**/*'

'@beapi/docs':
  - 'docs/*'
  - 'docs/**/*'

'@gh':
  - '.github/*'
  - '.github/**/*'
